[package]
name = "ccat-cryptor"
version = "0.1.0"
edition = "2021"

[dependencies]
aes-gcm = "0.10.3"
aes = "0.8.4"
block-modes = "0.9.1"
rand = "0.8.5"
hex = "0.4.3"
walkdir = "2.5.0"

[profile.release]
strip = true
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
